name: Build and push :main image

on:
  push:
    branches: [ master main ]
  pull_request:
    branches: [ master main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: build
      env:
      run: |
        echo 'seal-build' > .id
        make test
        make demo

